---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
      fabric8.io/git-commit: ae00cfc7e0057fb2f9a79cf3152a76840f6ac915
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=nexus-app&var-version=1.0.1
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/nexus-app.git
      fabric8.io/scm-url: http://github.com/fabric8-apps/nexus-app
      fabric8.io/git-branch: release-v1.0.1
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/nexus-app.git
      fabric8.io/scm-tag: nexus-app-1.0.0
    labels:
      provider: fabric8
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: 1.0.1
      group: io.fabric8.apps
    name: nexus
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
        provider: fabric8
        group: io.fabric8.apps
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: ae00cfc7e0057fb2f9a79cf3152a76840f6ac915
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=nexus-app&var-version=1.0.1
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/nexus-app.git
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/sonatype-work/storage"],"volumeMounts":[{"mountPath":"/sonatype-work/storage","name":"nexus-storage"}]}]'
          fabric8.io/scm-url: http://github.com/fabric8-apps/nexus-app
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v1.0.1
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/nexus-app.git
          fabric8.io/scm-tag: nexus-app-1.0.0
          maven.fabric8.io/source-url: jar:file:/home/jenkins/.mvnrepository/io/fabric8/apps/nexus-app/1.0.1/nexus-app-1.0.1.jar!/META-INF/fabric8/kubernetes.yml
        labels:
          provider: fabric8
          app: {{ template "fullname" . }}
          version: 1.0.1
          group: io.fabric8.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "{{ .Values.nexus.image.name }}:{{ .Values.nexus.image.tag }}"
          imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /content/repositories/
              port: 8081
            initialDelaySeconds: 1000
            timeoutSeconds: 10
          name: nexus
          ports:
          - containerPort: 8081
            name: http
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /content/repositories/
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /sonatype-work/storage
            name: nexus-storage
            readOnly: false
        volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-storage
