apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "name" . }}-efs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # Create this first!
    server: {{ .Values.nexus2Storage.efs.server }}
    path: "/{{ template "name" . }}"
