apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-storage-efs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # Create this first!
    server: {{ .Values.efs.server }}
    path: "/nexus-storage"
