apiVersion: v1
name: nexus2-storage
description: Chart that deploys PV and PVC for use with Nexus2 chart
version: 1.0.0
keywords:
  - nexus2
  - pvc
  - pv
  - kubernetes
home: https://github.com/stakater/chart-nexus2
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
